receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Prometheus: з цього endpoint-а буде читати сам Prometheus
  prometheus:
    endpoint: "0.0.0.0:9464"

  # Zipkin: сюди Collector кине трейси
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  # Elasticsearch: сюди підуть логи (і при бажанні метрики/трейси)
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "otel-logs"
    traces_index: "otel-traces"
    metrics_index: "otel-metrics"

processors:
  batch: {}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, elasticsearch]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, elasticsearch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
